In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
!pip install lxml

Collecting lxml
  Downloading lxml-6.0.2-cp311-cp311-win_amd64.whl.metadata (3.7 kB)
Downloading lxml-6.0.2-cp311-cp311-win_amd64.whl (4.0 MB)
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ---------- ----------------------------- 1.0/4.0 MB 25.4 MB/s eta 0:00:01
   ---------------------------------------- 4.0/4.0 MB 24.2 MB/s  0:00:00
Installing collected packages: lxml
Successfully installed lxml-6.0.2

In [5]:
df = pd.read_xml("basic_xml.xml")
df

   name  age      city
0  John   30  New York
1  Anna   25     Paris

In [15]:
d_complex = pd.read_xml("complex_xml_structures.xml")
d_complex

  name      city
0  USA  \n

city showing \n. so, going inside it

In [25]:
d_complex = pd.read_xml("complex_xml_structures.xml", xpath= ".//city")
d_complex

       name  person
0  New York     NaN

In [34]:
namespaces = {"ns" : "https://www.example.com"}
dataframe = pd.read_xml("/content/xml_namespace.xml", namespaces=namespaces)
dataframe

  name      city
0  USA  \n